site_name: ã‚ªãƒšãƒ¬ãƒ¼ãƒ†ã‚£ãƒ³ã‚°ã‚·ã‚¹ãƒ†ãƒ 
site_description: ã‚ªãƒšãƒ¬ãƒ¼ãƒ†ã‚£ãƒ³ã‚°ã‚·ã‚¹ãƒ†ãƒ ã®è³‡æ–™
site_url: https://cist-perating-system.netlify.app/
site_author: yusuke-ohmori
# repo_name: OHMORIYUSUKE/OS-lecture
# repo_url: https://github.com/OHMORIYUSUKE/OS-lecture
copyright: Â© 2022 yusuke-ohmori
license: MTI
# edit_uri: blob/main/document/docs/

nav:
  - "ç›®æ¬¡": "index.md"
  - "ã‚ªãƒšãƒ¬ãƒ¼ãƒ†ã‚£ãƒ³ã‚°ã‚·ã‚¹ãƒ†ãƒ ":
      - "æœ€çµ‚ç›®æ¨™": "os/index.md"
      - "AWS":
          - "AWSã¨ã¯": "os/aws/index.md"
          - "AWSã‚¢ã‚«ãƒ‡ãƒŸãƒ¼": "os/aws/aws-academy.md"
          - "EC2ã¨ã¯": "os/aws/ec2.md"
      - "Linux ã‚³ãƒãƒ³ãƒ‰":
          - "Linuxã¨ã¯": "os/linux/index.md"
          - "CLIã¨GUI": "os/linux/cli-gui.md"
          - "CLIå®Ÿè·µ": "os/linux/cmd-tutorial.md"
      - "ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£":
          - "ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ã¨ã¯": "os/security/index.md"
          - "ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ã‚°ãƒ«ãƒ¼ãƒ—ã¨ã¯": "os/security/security-group.md"
          - "IPã‚¢ãƒ‰ãƒ¬ã‚¹": "os/security/ip.md"
          - "ãƒãƒ¼ãƒˆ": "os/security/port.md"
          - "SSHã¨ã¯(å…¬é–‹éµãƒ»ç§˜å¯†éµ)": "os/security/ssh.md"
      - "ãƒŸãƒ‰ãƒ«ã‚¦ã‚§ã‚¢":
          - "ãƒŸãƒ‰ãƒ«ã‚¦ã‚§ã‚¢ã¨ã¯": "os/middleware/index.md"
          - "WEBã‚µãƒ¼ãƒãƒ¼": "os/middleware/web-server.md"
          - "Apach": "os/middleware/apach.md"
          - "ãƒ‡ãƒ¼ã‚¿ãƒ™ãƒ¼ã‚¹": "os/middleware/database.md"
          - "MySQL": "os/middleware/mysql.md"
      - "é™çš„ã‚³ãƒ³ãƒ†ãƒ³ãƒ„":
          - "é™çš„ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã¨ã¯": "os/static-content/index.md"
          - "HTML, CSS, JavaScritp": "os/static-content/html-css-js.md"
      - "å‹•çš„ã‚³ãƒ³ãƒ†ãƒ³ãƒ„":
          - "å‹•çš„ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã¨ã¯": "os/dynamic-content/index.md"
          - "PHP": "os/dynamic-content/php.md"
      - "EC2 ãƒãƒ¥ãƒ¼ãƒˆãƒªã‚¢ãƒ«":
          - "æ§‹ç¯‰ã™ã‚‹ã‚‚ã®": "os/ec2-tutorial/index.md"
          - "AWSã‚³ãƒ³ã‚½ãƒ¼ãƒ«": "os/ec2-tutorial/console.md"
          - "EC2ã‚’èµ·å‹•": "os/ec2-tutorial/ec2-start.md"
          - "EC2ã«ã‚¢ã‚¯ã‚»ã‚¹": "os/ec2-tutorial/ec2-ssh.md"
          - "Apachã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ãƒ»èµ·å‹•": "os/ec2-tutorial/apach-start.md"
          - "HTMLã‚’å…¬é–‹": "os/ec2-tutorial/public-html.md"
          - "PHPã‚’å…¬é–‹": "os/ec2-tutorial/public-php.md"
          - "MySQLã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ãƒ»èµ·å‹•": "os/ec2-tutorial/start-mysql.md"
          - "MySQLã‚’æ“ä½œ(åˆæœŸè¨­å®šãƒ»ãƒ†ãƒ¼ãƒ–ãƒ«ã‚’ä½œæˆ)": "os/ec2-tutorial/operation-mysql.md"
          - "PHPã‹ã‚‰ãƒ‡ãƒ¼ã‚¿ãƒ™ãƒ¼ã‚¹ã«ã‚¢ã‚¯ã‚»ã‚¹": "os/ec2-tutorial/get-db-data.md"
      - "ä»˜éŒ²":
          - "ãƒ›ãƒ¼ãƒ ": "os/appendix/index.md"
          - "ä»®æƒ³ç’°å¢ƒ(docker)": "os/appendix/docker.md"
          - "ãƒ‡ãƒ¼ã‚¿ãƒ™ãƒ¼ã‚¹(Redis, PostgreSQL)": "os/appendix/redis.md"
          - "WEBã‚µãƒ¼ãƒãƒ¼(nginx)": "os/appendix/nginx.md"
          - "ã‚¢ãƒ—ãƒªã‚±ãƒ¼ã‚·ãƒ§ãƒ³(Java, Python)": "os/appendix/java-python.md"
          - "ãƒ­ã‚°(Apach)": "os/appendix/apach-log.md"
  - "ãƒ©ã‚¤ã‚»ãƒ³ã‚¹ğŸ”‘": "license.md"

plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

theme:
  name: material
  language: "ja"
  # favicon: assets/aws_icon.png
  # logo: assets/aws_icon.png
  highlightjs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - search.highlight
    - search.suggest
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - pymdownx.keys:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - nl2br
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
# extra:
#   social:
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/uutan1108
#     - icon: fontawesome/brands/github
#       link: https://github.com/OHMORIYUSUKE
